version: "3.5"

services:
  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
    networks:
      - project-manager-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3020:3020
    networks:
      - project-manager-network
    depends_on:
      - database

networks:
  project-manager-network:
    driver: bridge
