CREATE TYPE "position_type" AS ENUM (
  'developer',
  'designer',
  'techlead',
  'devops',
  'qa',
  'agile_lead'
);

CREATE TYPE "project_type" AS ENUM (
  'parent',
  'subproject'
);

CREATE TYPE "user_role" AS ENUM (
  'admin',
  'editor',
  'viewer'
);

CREATE TYPE "role_permission" AS ENUM (
  'create',
  'read',
  'update',
  'delete'
);

CREATE TABLE "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "project_id" integer DEFAULT null,
  "title" varchar NOT NULL,
  "description" varchar,
  "status" varchar DEFAULT 'active' NOT NULL,
  "type" project_type DEFAULT project_type'parent' NOT NULL,
  "started_at" timestamptz,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "ended_at" timestamptz,
  "created_by" integer NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar,
  "password" varchar,
  "created_at" timestamptz DEFAULT now(),
  "role" user_role DEFAULT user_role'viewer'
);

CREATE TABLE "tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "project_id" integer NOT NULL,
  "title" varchar,
  "description" text,
  "is_finished" bool,
  "ended_at" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "created_by" integer NOT NULL
);

CREATE TABLE "collaborators" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "position" position_type
);

CREATE TABLE "estimations" (
  "task_id" integer NOT NULL,
  "collaborator_id" integer NOT NULL,
  "task_hour" integer
);

COMMENT ON COLUMN "tasks"."description" IS 'Content of the task';

ALTER TABLE "tasks" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "estimations" ADD FOREIGN KEY ("collaborator_id") REFERENCES "collaborators" ("id");

ALTER TABLE "estimations" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "tasks" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

CREATE INDEX "projects_created_by_index" ON "projects" ("created_by");

CREATE INDEX "tasks_created_by_index" ON "tasks" ("created_by");
